version: '3.8'
services:
    jenkins:
        image: jenkinsci/blueocean
        restart: always
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins:/var/jenkins_home