version: '3.7'
services:
    jenkins:
        build: .
        restart: always
        ports:
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins:/root/.jenkins